// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mbwprjummulcvbmhfppa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1id3ByanVtbXVsY3ZibWhmcHBhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2ODc1NDAsImV4cCI6MjA1OTI2MzU0MH0.4F0pAzQ3JwJiMrv9oWa-QQoPGaow45cn3mywx2PJzRU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);